/* Auto-generated by cbindgen - do not edit manually */

#ifndef BINDLE_H
#define BINDLE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

/**
 * Opaque handle to a Bindle archive.
 */
typedef struct BindleContext BindleContext;

struct BindleContext *bindle_open(const char *path);

/**
 * Adds a new entry. Returns true on success.
 */
bool bindle_add(struct BindleContext *ctx,
                const char *name,
                const uint8_t *data,
                size_t data_len,
                bool compress);

/**
 * Commits changes to disk.
 */
bool bindle_save(struct BindleContext *ctx);

/**
 * Frees BindleContext
 */
void bindle_free(struct BindleContext *ctx);

uint8_t *bindle_read(struct BindleContext *ctx, const char *name, size_t *out_len);

const uint8_t *bindle_read_uncompressed_direct(struct BindleContext *ctx,
                                               const char *name,
                                               size_t *out_len);

void bindle_free_buffer(uint8_t *ptr, size_t len);

size_t bindle_length(const struct BindleContext *ctx);

/**
 * Returns the name of the entry at the given index.
 * The string is owned by the Bindle; the caller must NOT free it.
 */
const char *bindle_entry_name(const struct BindleContext *ctx, size_t index, size_t *len);

#endif  /* BINDLE_H */
