/* Auto-generated by cbindgen - do not edit manually */

#ifndef BINDLE_H
#define BINDLE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

/**
 * Compression mode for entries.
 */
enum BindleCompress {
  /**
   * No compression.
   */
  BindleCompressNone = 0,
  /**
   * Zstandard compression.
   */
  BindleCompressZstd = 1,
  /**
   * Automatically compress if entry is larger than 2KB threshold.
   * Note: This is never stored on disk, only used as a policy hint.
   */
  BindleCompressAuto = 2,
};
typedef uint8_t BindleCompress;

/**
 * A binary archive for collecting files.
 *
 * Uses memory-mapped I/O for fast reads, supports optional zstd compression, and handles updates via shadowing.
 * Files can be added incrementally without rewriting the entire archive.
 *
 * # Example
 *
 * ```no_run
 * use bindle_file::{Bindle, Compress};
 *
 * let mut archive = Bindle::open("data.bndl")?;
 * archive.add("file.txt", b"data", Compress::None)?;
 * archive.save()?;
 * # Ok::<(), std::io::Error>(())
 * ```
 */
typedef struct Bindle Bindle;

/**
 * A streaming reader for archive entries.
 *
 * Created by the archive's `reader()` method. Automatically decompresses compressed entries and tracks CRC32 for integrity verification.
 *
 * # Example
 *
 * ```no_run
 * # use bindle_file::Bindle;
 * # let archive = Bindle::open("data.bndl")?;
 * let mut reader = archive.reader("file.txt")?;
 * std::io::copy(&mut reader, &mut std::io::stdout())?;
 * reader.verify_crc32()?;
 * # Ok::<(), std::io::Error>(())
 * ```
 */
typedef struct BindleReader BindleReader;

/**
 * A streaming writer for adding entries to an archive.
 *
 * Created by [`Bindle::writer()`]. Automatically compresses data if requested and computes CRC32 for integrity verification.
 *
 * The writer must be closed with [`close()`](Writer::close) or will be automatically closed when dropped. After closing, call [`Bindle::save()`] to commit the index.
 *
 * # Example
 *
 * ```no_run
 * use std::io::Write;
 * use bindle_file::{Bindle, Compress};
 *
 * let mut archive = Bindle::open("data.bndl")?;
 * let mut writer = archive.writer("file.txt", Compress::None)?;
 * writer.write_all(b"data")?;
 * writer.close()?;
 * archive.save()?;
 * # Ok::<(), std::io::Error>(())
 * ```
 */
typedef struct BindleWriter BindleWriter;

/**
 * Open a bindle file from disk, the path paramter should be NUL terminated
 */
struct Bindle *bindle_open(const char *path);

/**
 * Adds a new entry, the name should be NUL terminated, will the data can contain NUL characters since the length
 * is provided
 */
bool bindle_add(struct Bindle *ctx,
                const char *name,
                const uint8_t *data,
                size_t data_len,
                BindleCompress compress);

/**
 * Adds a new entry, the name should be NUL terminated, will the data can contain NUL characters since the length
 * is provided
 */
bool bindle_add_file(struct Bindle *ctx,
                     const char *name,
                     const char *path,
                     BindleCompress compress);

/**
 * Save any changed to disk
 */
bool bindle_save(struct Bindle *ctx);

/**
 * Close an open bindle file
 */
void bindle_close(struct Bindle *ctx);

/**
 * Read a value from a bindle file in memory, returns a pointer that should be freed with
 * `bindle_free_buffer`
 */
uint8_t *bindle_read(struct Bindle *ctx_ptr, const char *name, size_t *out_len);

/**
 * Used to free the results from `bindle_read`
 */
void bindle_free_buffer(uint8_t *ptr);

/**
 * Directly read an uncompressed entry from disk, returns NULL if the entry is compressed or doesn't exist
 */
const uint8_t *bindle_read_uncompressed_direct(struct Bindle *ctx,
                                               const char *name,
                                               size_t *out_len);

/**
 * Get the number of entries in a bindle file
 */
size_t bindle_length(const struct Bindle *ctx);

/**
 * Returns the name of the entry at the given index.
 * The string is owned by the Bindle; the caller must NOT free it.
 */
const char *bindle_entry_name(const struct Bindle *ctx, size_t index, size_t *len);

/**
 * Compact and rewrite bindle file
 */
bool bindle_vacuum(struct Bindle *ctx);

bool bindle_unpack(struct Bindle *ctx, const char *dest_path);

bool bindle_pack(struct Bindle *ctx, const char *src_path, BindleCompress compress);

bool bindle_exists(const struct Bindle *ctx, const char *name);

/**
 * Remove an entry from the index.
 * The data remains in the file until bindle_vacuum is called.
 * Returns true if the entry existed and was removed, false otherwise.
 */
bool bindle_remove(struct Bindle *ctx, const char *name);

/**
 * Create a new Writer, while the stream is active (until bindle_stream_finish is called), the
 * Bindle struct should not be accessed.
 */
struct BindleWriter *bindle_writer_new(struct Bindle *ctx,
                                       const char *name,
                                       BindleCompress compress);

bool bindle_writer_write(struct BindleWriter *stream, const uint8_t *data, size_t len);

bool bindle_writer_close(struct BindleWriter *stream);

struct BindleReader *bindle_reader_new(const struct Bindle *ctx, const char *name);

ptrdiff_t bindle_reader_read(struct BindleReader *reader, uint8_t *buffer, size_t buffer_len);

/**
 * Verify the CRC32 of data read from the reader.
 * Should be called after reading all data to ensure integrity.
 * Returns true if CRC32 matches, false otherwise.
 */
bool bindle_reader_verify_crc32(const struct BindleReader *reader);

void bindle_reader_close(struct BindleReader *reader);

#endif  /* BINDLE_H */
